"""API routes and schemas."""

from agent_api.api.routes import router
from agent_api.api.schemas import (
    AgentCase,
    AgentMessageForUser,
    AgentOutputForSystem,
    ArtifactInput,
    ArtifactResponse,
    ChatResponse,
    ClarificationQuestionResponse,
    DocumentSelectionRequest,
    EditInstruction,
    EditOperation,
    PageContextRequest,
    RequestType,
    SSEEvent,
    SSEEventType,
    StorageConfigRequest,
    TemplateField,
    TemplateRequest,
    ToolResultResponse,
    UnifiedChatRequest,
)

__all__ = [
    "router",
    "AgentCase",
    "AgentMessageForUser",
    "AgentOutputForSystem",
    "ArtifactInput",
    "ArtifactResponse",
    "ChatResponse",
    "ClarificationQuestionResponse",
    "DocumentSelectionRequest",
    "EditInstruction",
    "EditOperation",
    "PageContextRequest",
    "RequestType",
    "SSEEvent",
    "SSEEventType",
    "StorageConfigRequest",
    "TemplateField",
    "TemplateRequest",
    "ToolResultResponse",
    "UnifiedChatRequest",
]
